from id3 import Id3Estimator, export_graphviz
import numpy as np
import random

# nazwy cech
feature_names = ["danie", "na ciepło", "z mięsem", "na słodko", "kwaśne", "alkoholowe", "czekoladowe",]

# przypadki testowe z wartoĹ›ciami cech:
X = np.array([

    # barszcz
    ["zupa", 0, 0, 0, 0, 0, 0],
    ["zupa", 0, 0, 0, 0, 0, 0],
    ["zupa", 2, 0, 0, 0, 0, 0],
    ["zupa", 1, 0, 0, 0, 0, 0],
    ["zupa", 2, 0, 0, 0, 0, 0],
    ["zupa", 0, 0, 0, 0, 0, 0],
    ["zupa", 1, 0, 0, 0, 0, 0],
    ["zupa", 0, 0, 0, 0, 0, 0],
    ["zupa", 4, 0, 0, 0, 0, 0],
    ["zupa", 2, 0, 0, 0, 0, 0],

    # zupa pomidorowa
    ["zupa", 10, 3, 0, 0, 0, 0],
    ["zupa", 9, 2, 0, 0, 0, 0],
    ["zupa", 5, 0, 0, 0, 0, 0],
    ["zupa", 6, 4, 0, 0, 0, 0],
    ["zupa", 8, 2, 0, 0, 0, 0],
    ["zupa", 9, 5, 0, 0, 0, 0],
    ["zupa", 10, 3, 0, 0, 0, 0],
    ["zupa", 7, 0, 0, 0, 0, 0],
    ["zupa", 6, 2, 0, 0, 0, 0],
    ["zupa", 9, 1, 0, 0, 0, 0],

    # żurek
    ["zupa", 10, 5, 0, 0, 0, 0],
    ["zupa", 9,  7, 0, 0, 0, 0],
    ["zupa", 5,  9, 0, 0, 0, 0],
    ["zupa", 6, 10, 0, 0, 0, 0],
    ["zupa", 8, 10, 0, 0, 0, 0],
    ["zupa", 9,  5, 0, 0, 0, 0],
    ["zupa", 10, 10, 0, 0, 0, 0],
    ["zupa", 7,  7, 0, 0, 0, 0],
    ["zupa", 6, 10, 0, 0, 0, 0],
    ["zupa", 9, 10, 0, 0, 0, 0],

    # devolay
    ["danie główne", 0,  5, 0, 0, 0, 0],
    ["danie główne", 0,  7, 0, 0, 0, 0],
    ["danie główne", 0,  9, 0, 0, 0, 0],
    ["danie główne", 0, 10, 0, 0, 0, 0],
    ["danie główne", 0, 10, 0, 0, 0, 0],
    ["danie główne", 0,  5, 0, 0, 0, 0],
    ["danie główne", 0, 10, 0, 0, 0, 0],
    ["danie główne", 0,  7, 0, 0, 0, 0],
    ["danie główne", 0, 10, 0, 0, 0, 0],
    ["danie główne", 0, 10, 0, 0, 0, 0],

    # pierogi
    ["danie główne", 0, 5, 10, 0, 0, 0],
    ["danie główne", 0, 3, 8, 0, 0, 0],
    ["danie główne", 0, 2, 7, 0, 0, 0],
    ["danie główne", 0, 1, 8, 0, 0, 0],
    ["danie główne", 0, 0, 5, 0, 0, 0],
    ["danie główne", 0, 0, 10, 0, 0, 0],
    ["danie główne", 0, 1, 10, 0, 0, 0],
    ["danie główne", 0, 4, 8, 0, 0, 0],
    ["danie główne", 0, 3, 9, 0, 0, 0],
    ["danie główne", 0, 2, 6, 0, 0, 0],

    # spaghetti
    ["danie główne", 0, 5, 4, 0, 0, 0],
    ["danie główne", 0, 3, 3, 0, 0, 0],
    ["danie główne", 0, 2, 0, 0, 0, 0],
    ["danie główne", 0, 1, 0, 0, 0, 0],
    ["danie główne", 0, 0, 2, 0, 0, 0],
    ["danie główne", 0, 0, 1, 0, 0, 0],
    ["danie główne", 0, 1, 1, 0, 0, 0],
    ["danie główne", 0, 4, 0, 0, 0, 0],
    ["danie główne", 0, 3, 3, 0, 0, 0],
    ["danie główne", 0, 2, 2, 0, 0, 0],

    # Herbata
    ["napoje", 10, 0, 0, 6, 0, 0],
    ["napoje", 9, 0, 0, 9, 0, 0],
    ["napoje", 6, 0, 0, 10, 0, 0],
    ["napoje", 8, 0, 0, 9, 0, 0],
    ["napoje", 7, 0, 0, 6, 0, 0],
    ["napoje", 9, 0, 0, 5, 0, 0],
    ["napoje", 10, 0, 0, 6, 0, 0],
    ["napoje", 10, 0, 0, 9, 0, 0],
    ["napoje", 8, 0, 0, 8, 0, 0],
    ["napoje", 6, 0, 0, 10, 0, 0],

    # kawa
    ["napoje", 10, 0, 0, 3, 0, 0],
    ["napoje", 9, 0, 0, 2, 0, 0],
    ["napoje", 6, 0, 0, 4, 0, 0],
    ["napoje", 8, 0, 0, 4, 0, 0],
    ["napoje", 7, 0, 0, 3, 0, 0],
    ["napoje", 9, 0, 0, 1, 0, 0],
    ["napoje", 10, 0, 0, 0, 0, 0],
    ["napoje", 10, 0, 0, 1, 0, 0],
    ["napoje", 8, 0, 0, 2, 0, 0],
    ["napoje", 6, 0, 0, 1, 0, 0],

    # sok pomaranczowy
    ["napoje", 2, 0, 0, 0, 2, 0],
    ["napoje", 1, 0, 0, 0, 1, 0],
    ["napoje", 5, 0, 0, 0, 0, 0],
    ["napoje", 4, 0, 0, 0, 3, 0],
    ["napoje", 2, 0, 0, 0, 2, 0],
    ["napoje", 1, 0, 0, 0, 0, 0],
    ["napoje", 0, 0, 0, 0, 1, 0],
    ["napoje", 0, 0, 0, 0, 2, 0],
    ["napoje", 3, 0, 0, 0, 1, 0],
    ["napoje", 2, 0, 0, 0, 4, 0],

    # wino
    ["napoje", 2, 0, 0, 0, 10, 0],
    ["napoje", 1, 0, 0, 0, 9, 0],
    ["napoje", 5, 0, 0, 0, 10, 0],
    ["napoje", 4, 0, 0, 0, 6, 0],
    ["napoje", 2, 0, 0, 0, 10, 0],
    ["napoje", 1, 0, 0, 0, 10, 0],
    ["napoje", 0, 0, 0, 0, 10, 0],
    ["napoje", 0, 0, 0, 0, 8, 0],
    ["napoje", 3, 0, 0, 0, 6, 0],
    ["napoje", 2, 0, 0, 0, 8, 0],

    # kompot truskawkowy
    ["napoje", 2, 0, 10, 0, 2, 0],
    ["napoje", 1, 0, 10, 0, 1, 0],
    ["napoje", 5, 0, 9, 0, 0, 0],
    ["napoje", 4, 0, 8, 0, 3, 0],
    ["napoje", 2, 0, 10, 0, 2, 0],
    ["napoje", 1, 0, 9, 0, 0, 0],
    ["napoje", 0, 0, 7, 0, 1, 0],
    ["napoje", 0, 0, 8, 0, 2, 0],
    ["napoje", 3, 0, 6, 0, 1, 0],
    ["napoje", 2, 0, 8, 0, 4, 0],

    # ciasto czekoladowe
    ["deser", 0, 0, 0, 0, 0, 10],
    ["deser", 0, 0, 0, 0, 0, 9],
    ["deser", 0, 0, 0, 0, 0, 10],
    ["deser", 0, 0, 0, 0, 0, 8],
    ["deser", 0, 0, 0, 0, 0, 10],
    ["deser", 0, 0, 0, 0, 0, 9],
    ["deser", 0, 0, 0, 0, 0, 10],
    ["deser", 0, 0, 0, 0, 0, 7],
    ["deser", 0, 0, 0, 0, 0, 10],
    ["deser", 0, 0, 0, 0, 0, 8],

    # sernik
    ["deser", 0, 0, 0, 0, 0, 4],
    ["deser", 0, 0, 0, 0, 0, 3],
    ["deser", 0, 0, 0, 0, 0, 2],
    ["deser", 0, 0, 0, 0, 0, 1],
    ["deser", 0, 0, 0, 0, 0, 0],
    ["deser", 0, 0, 0, 0, 0, 5],
    ["deser", 0, 0, 0, 0, 0, 4],
    ["deser", 0, 0, 0, 0, 0, 2],
    ["deser", 0, 0, 0, 0, 0, 1],
    ["deser", 0, 0, 0, 0, 0, 1],
])

y = np.array(["barszcz",
              "barszcz",
              "barszcz",
              "barszcz",
              "barszcz",
              "barszcz",
              "barszcz",
              "barszcz",
              "barszcz",
              "barszcz",
              "zupa pomidorowa",
              "zupa pomidorowa",
              "zupa pomidorowa",
              "zupa pomidorowa",
              "zupa pomidorowa",
              "zupa pomidorowa",
              "zupa pomidorowa",
              "zupa pomidorowa",
              "zupa pomidorowa",
              "zupa pomidorowa",
              "żurek",
              "żurek",
              "żurek",
              "żurek",
              "żurek",
              "żurek",
              "żurek",
              "żurek",
              "żurek",
              "żurek",
              "devolay",
              "devolay",
              "devolay",
              "devolay",
              "devolay",
              "devolay",
              "devolay",
              "devolay",
              "devolay",
              "devolay",
              "pierogi",
              "pierogi",
              "pierogi",
              "pierogi",
              "pierogi",
              "pierogi",
              "pierogi",
              "pierogi",
              "pierogi",
              "pierogi",
              "spaghetti",
              "spaghetti",
              "spaghetti",
              "spaghetti",
              "spaghetti",
              "spaghetti",
              "spaghetti",
              "spaghetti",
              "spaghetti",
              "spaghetti",
              "Herbata z cytryną",
              "Herbata z cytryną",
              "Herbata z cytryną",
              "Herbata z cytryną",
              "Herbata z cytryną",
              "Herbata z cytryną",
              "Herbata z cytryną",
              "Herbata z cytryną",
              "Herbata z cytryną",
              "Herbata z cytryną",
              "kawa",
              "kawa",
              "kawa",
              "kawa",
              "kawa",
              "kawa",
              "kawa",
              "kawa",
              "kawa",
              "kawa",
              "piwo",
              "piwo",
              "piwo",
              "piwo",
              "piwo",
              "piwo",
              "piwo",
              "piwo",
              "piwo",
              "piwo",
              "wino",
              "wino",
              "wino",
              "wino",
              "wino",
              "wino",
              "wino",
              "wino",
              "wino",
              "wino",
              "kompot truskawkowy",
              "kompot truskawkowy",
              "kompot truskawkowy",
              "kompot truskawkowy",
              "kompot truskawkowy",
              "kompot truskawkowy",
              "kompot truskawkowy",
              "kompot truskawkowy",
              "kompot truskawkowy",
              "kompot truskawkowy",
              "ciasto czekoladowe",
              "ciasto czekoladowe",
              "ciasto czekoladowe",
              "ciasto czekoladowe",
              "ciasto czekoladowe",
              "ciasto czekoladowe",
              "ciasto czekoladowe",
              "ciasto czekoladowe",
              "ciasto czekoladowe",
              "ciasto czekoladowe",
              "sernik",
              "sernik",
              "sernik",
              "sernik",
              "sernik",
              "sernik",
              "sernik",
              "sernik",
              "sernik",
              "sernik",
              ])


# tworzenie drzewa decyzyjnego
clf = Id3Estimator()
# fit - synonim do "find patterns in data"
clf.fit(X, y, check_input=True)

export_graphviz(clf.tree_, "test2.dot", feature_names)
